apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  annotations:
    {{- if .Values.readinessProbe }}
    {{- if .Values.readinessProbe.httpGet }}
    {{- if .Values.readinessProbe.httpGet.path }}
    alb.ingress.kubernetes.io/healthcheck-path: "{{ .Values.readinessProbe.httpGet.path }}"
    {{- end }}
    {{- end }}
    {{- end }}
  {{- with merge .Values.service.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "<CHARTNAME>.selectorLabels" . | nindent 4 }}
